### ISSUE TITLE
Update Singleton 

### ISSUE THREAD

**Issue by eternalko** [braziljs/js-the-right-way#167]
Hi, 

I think that it is worth removing Singleton from recommended design patterns. Even in the book there is a final word about it:

> Whilst the Singleton has valid uses, often **when we find ourselves needing it in JavaScript it's a sign that we may need to re-evaluate our design**.

> They're often an indication that modules in a system are either tightly coupled or that logic is overly spread across multiple parts of a codebase. Singletons can be more difficult to test due to issues ranging from hidden dependencies, the difficulty in creating multiple instances, difficulty in stubbing dependencies and so on.

They create a *hidden* (not explicit) global state and global state dependency. And this will make everyone's life miserable. In real world JS a module pattern can and should be used. It is a de-facto standard. And it gives all the benefits of a singleton without the downsides.

**Comment by eternalko** [comment]
Since there is no feedback, will close this issue

**Comment by gnuwilliam** [comment]
Hey @eternalko, sorry for taking so long to answer you.

I do agree with you that Singleton would create a really bad environment in JavaScript, but at the same time, it's still a design pattern, and there are cases and cases. Maybe for a really specific reason, someone would find it useful somehow.

Besides that, I think it's helpful having the link on the website, so users can get more information about why they shouldn't use it in most cases. It's not in the "recommended design patterns", it's inside Patterns, under "Creational Design Patterns" sub-section. There's no such thing as "recommended design patterns", they're specific solution to specific problems.

But thanks for taking the time to expose your concern.

Best,
- William

**Comment by eternalko** [comment]
@gnuwilliam, battle with singletons is as old as any IT holy war. 

Any discussion I had in my life about them always ends up:
'ok, now I see why **classical** singleton is an antipattern'.

Antipattern is also a pattern. And don't take my word for it. 
A [link](http://misko.hevery.com/2008/10/21/dependency-injection-myth-reference-passing/)] from the books last paragraph. 

Most new programmers read books/articles/code and all they learn about patterns is "use singleton everywhere". I make it anecdotal, but this not so far away from truth. 

IMO any singleton reference should be with a big red warning sign at start.
