### ISSUE TITLE
Divulgação do repositório

### ISSUE THREAD

**Issue by pedropolisenso** [braziljs/js-the-right-way#170]
Acho legal começarmos a informar nas comunidade sobre **js-the-right-way** seria de muito últil para alguns. Pelo meu ponto de vista é um projeto não muito divulgado que poderia ser tornar popular nas comindades e ajudar mais pessoas. :+1:

**Comment by gnuwilliam** [comment]
Fala, @pedropolisenso!

Cara, seria bem legal ter ajuda nessa divulgação, sim. Porém, ele já foi divulgado diversas vezes em varias mailing-lists, grupos, e também newsletters.

O projeto é muito popular fora do Brasil, mas aqui ainda precisamos ganhar espaço. 
Acredito que com a tradução em pt_BR consigamos atingir um resultado melhor, apesar disso me deixar um pouco desapontado, pois o inglês não deveria ser uma barreira, mas sim um desafio.

De qualquer forma, sinta-se a vontade para divulgar onde quer que esteja pensando em fazê-lo, tenho certeza que será de grande ajuda.

Valeu!

**Comment by pedropolisenso** [comment]
Sim com certeza, compreendo. Já mandaram um PR de tradução do README.md e
da index mas não deram o merge
Em 06/02/2015 13:16, "William Oliveira" <notifications@github.com> escreveu:

**Comment by gnuwilliam** [comment]
Sim, estou ciente. Falta revisar, e pretendo fazer isso o mais breve possivel.

**Comment by pedropolisenso** [comment]
Perfeito @gnuwilliam vamos aguardar a aprovação do PR. E quanto ao lance de divulgar mais, disse porque nunca havia visto nas comunidades alguém falando ou comentando. Mas me organizei durante um tempo e a partir desse ano estou querendo contribuir mais para projetos Opens, saca? 

Essa semana mesmo vou mandar um PR para fixar o menu (issue #169), facilitando na navegação do usuário. E depois que o projeto traduzido for aprovado, vai facilitar mais ainda. Conte comigo no que precisar. Minha meta de contribuir todos os dias com projetos, mesmo que seja apenas com issue.
