### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by item4** [braziljs/js-the-right-way#185]
Hello.

I find this repo from HN today. I look at it and I think "I must translate it. It will be nice work for my study and global js culture.".

I'm Korean. Although I can't English well, I think I can translate it with some reference from dictionaries and some advice from its contributer. And I think if you decide to i18n this page, there will be with many contributors.

Please reply your opinion.

**Comment by AlperenTalaslioglu** [comment]
Yeah, if they confirm, I can translate entire page to Turkish. There will be more contributors to different language translations. Your idea is great :) Hope they will confirm this idea :+1:

**Comment by allanesquina** [comment]
Hey guys, amazing, I need one responsible for each language, cause I'm Brazilian, if you accept, you can do this work. What do you think?

**Comment by AlperenTalaslioglu** [comment]
@allanesquina I can translate all page to Turkish :+1:

**Comment by appleboy** [comment]
@allanesquina I can translate all page to `Traditional Chinese`

**Comment by item4** [comment]
@allanesquina I want to do it. :+1:

**Comment by seoh** [comment]
do you need a participant in Korean?

**Comment by item4** [comment]
@seoh you must do it with me =3=3

**Comment by allanesquina** [comment]
Fine, I'll create a new branch called i18n with an translation's structure and then we can work on it. 
Good luck, soldiers! :+1:

**Comment by AlperenTalaslioglu** [comment]
@allanesquina We are waiting your branch create :+1:

**Comment by ceoaliongroo** [comment]
:+1:

**Comment by seoh** [comment]
:+1:

**Comment by ujuc** [comment]
:+1:

**Comment by haruair** [comment]
Such a great idea :+1:

**Comment by item4** [comment]
@allanesquina Can we use i18n branch now?

**Comment by AlperenTalaslioglu** [comment]
I think no. "Please Wait" was written.

**Comment by item4** [comment]
Someone make a PR already. #189

**Comment by AlperenTalaslioglu** [comment]
So lets everyone create Pull Request :+1:

**Comment by item4** [comment]
I will wait until ready to go.

before show time, I suggest to fork and change my [google docs sheet](https://docs.google.com/spreadsheets/d/10Os0YvjHo3OOpW4QENh35MKGNd8vAqQpc6KbfymAU5U/edit?usp=sharing).

[Korean branch is here.](https://docs.google.com/spreadsheets/d/1rwNMrZ9pGg8CP7-Z8BBXUaoqE_yntPDcc2Fwb0FZlBU/edit?usp=sharing)

**Comment by allanesquina** [comment]
Hi guys, i'm sorry I made you wait, the .json file is incomplete, there's one item for each category, so I'll accept all pull requests now, but please, when I complete this file, be sure that your file be completed too. 
:+1:

**Comment by allanesquina** [comment]
Hey Soldiers, I fixed the workflow, now we can use **grunt server** to work. :+1:

**Comment by allanesquina** [comment]
Hey, the file **en-us.json** is completed. \o/
Thanks @gabrielfurini :+1:

**Comment by ivanbanov** [comment]
I'm gonna translate to portuguese folks!

**Comment by allanesquina** [comment]
Welcome to army @ivanbanov! :+1:

**Comment by allanesquina** [comment]
Soldiers, please, help us to decide what kind of flag to use on the select element! 
#194
