### ISSUE TITLE
[i18n] Language selector

### ISSUE THREAD

**Issue by gabrielfurini** [braziljs/js-the-right-way#194]
Hey guys, translate the project it's a good idea! Did you already think about a language selector? If you want, I'm able to help.

**Comment by allanesquina** [comment]
Not yet, what do you proposes?

**Comment by gabrielfurini** [comment]
I was thinking in a simple drop-down on top of the page. Could be clean and useful, following the visual identity of project. What do you think?

**Comment by allanesquina** [comment]
I liked, I was studying the case and I found this dropdown on codepen.io:
http://codepen.io/daniesy/pen/pfxFi
It's a good dropdown, would be interesting if it had a flag of the country as well, isn't?

**Comment by gabrielfurini** [comment]
It's funny... you posted a drop-down using just CSS, and this project is just about JS. But I agree with you. If CSS can do the work by itself, why not?

And yes, I was thinking to put flags too. In this case, we will need to have flag images. There are many kits of flag-icons available for free. We will need to choose one to maintain uniformity.
What about if a make a test and send it to you as PR?

**Comment by appleboy** [comment]
It is awesome drop-down using just css. :+1:

**Comment by allanesquina** [comment]
Well done, we need to decide what kind of flag to use. What if we put here the options and then, make the decision together?

**Comment by gabrielfurini** [comment]
I found an open-source project with svg icons, flatten designed, tested and with sass/less support ready: [flag-icon-css project](http://lipis.github.io/flag-icon-css/)

**Comment by allanesquina** [comment]
I liked, lets see what the soldiers think.

**Comment by gabrielfurini** [comment]
I made some tests and implemented locally this dropdown:
![languageselector](https://cloud.githubusercontent.com/assets/1728387/8640640/dac43654-28d5-11e5-9a6c-506b59e6d8fe.png)

Do you like it? I accept suggestions.

**Comment by allanesquina** [comment]
Yes, it's good, but what if you put this below of the 'the right way' element, centered? What do you think? Is it more visible?

**Comment by allanesquina** [comment]
Hi man, I'll merge **i18n** with **master** next weekend, can you commit your changes and make a PR?

**Comment by gabrielfurini** [comment]
Yes, I can. I'm gonna do this ASAP.

**Comment by allanesquina** [comment]
:zap:

**Comment by unluisco** [comment]
I do not agree with the flags, it is not a fair way to display the languages

**Comment by item4** [comment]
I do agree with @unluisco too.

**Comment by allanesquina** [comment]
Hi Soldiers, well, I agree with @unluisco too, so, let's only keep the languages names.
Is it good for you @gabrielfurini?

**Comment by gabrielfurini** [comment]
It really makes sense. But there's a change to be done on mobile version: just the flags are visible.
