### ISSUE TITLE
mocha testing tools listed twice in i18n branch es-es

### ISSUE THREAD

**Issue by item4** [braziljs/js-the-right-way#197]
It affect other branches. I build ko-kr for test and I see it.

**Comment by item4** [comment]
@ceoaliongroo please check it

**Comment by ceoaliongroo** [comment]
I think already fixed, https://github.com/braziljs/js-the-right-way/pull/195/files need to be merge. Could you check @allanesquina?

**Comment by allanesquina** [comment]
Yup, it's fixed. Can you check @item4?

**Comment by item4** [comment]
@allanesquina yes, it fixed. please close this issue after your checking

**Comment by allanesquina** [comment]
:ok:
