### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by pedropolisenso** [braziljs/js-the-right-way#200]
Às vezes acho este projeto meio parado, tem bastante PR encaminhado e nenhum aceito, este é um projeto legal da comunidades, podemos manter o mesmo em funcionamento e atualizado!

**Comment by allanesquina** [comment]
@pedropolisenso, sim, as vezes é difícil manter um projeto open source pois exige tempo e dedicação (fora os gastos que saem do nosso bolso), principalmente em um projeto como esse onde PR e novas issues são abertas quase todos os dias. Analizar a mudança, verificar o conteúdo e responder a todos nem sempre é uma tarefa fácil. Em virtude a esta dificuldade, o criador do projeto (@gnuwilliam) colocou mais um responsável (eu) com o intuito de manter o projeto atualizado e com novas idéias. Eu concordo com você, por isso estou aqui, para dar continuidade a esse trabalho maravilhoso que todos vocês vem ajudando a construir.

**Comment by pedropolisenso** [comment]
Show @allanesquina irado, confesso que até eu havia esquecido deste projeto, criei uma issue para fixar o menu, facilitando a navegação, dei uma olhadas nos PR e vi que ja tem a tradução de EN para PT, pois tem uma galera ainda que precisa aprender o ingles, enfim. Só quero que saiba que pode contar comigo para este projeto.

**Comment by allanesquina** [comment]
Bem vindo ao time @pedropolisenso!  :+1:
