### ISSUE TITLE
jsconf 

### ISSUE THREAD

**Issue by huei90** [braziljs/js-the-right-way#202]
How about adding jsconf (https://www.youtube.com/user/jsconfeu) in the podcast list?

<img src="https://yt3.ggpht.com/-lLQJVHClDZM/AAAAAAAAAAI/AAAAAAAAAAA/3sWsdPc8lAs/s100-c-k-no/photo.jpg"/>

**Comment by allanesquina** [comment]
Hi @huei90, good, I think you can add it in the screencast section, you can follow the podcast elements pattern, adding a box instead a image. 
You can change this files:
https://github.com/braziljs/js-the-right-way/blob/i18n/i18n/en-us/en-us.json
https://github.com/braziljs/js-the-right-way/blob/i18n/templates/index.html
Can you do it for us?

**Comment by huei90** [comment]
Sure, I will do it!

**Comment by huei90** [comment]
Done, should I change the master branch too?

**Comment by allanesquina** [comment]
Thanks @huei90 ! :+1:

**Comment by huei90** [comment]
:+1:
