### ISSUE TITLE
pt-br revision 

### ISSUE THREAD

**Issue by allanesquina** [braziljs/js-the-right-way#209]
Hi @ruanltbg, good job, now I'm putting here some points to review: :+1: 
@ivanbanov

# Todo
* Some words need to be in original language for a better understanding. (e.g. **engine**)
* Some words need to accent correction

**Comment by ruanltbg** [comment]
@allanesquina In the case you prefer "Engine de games" or "Game Engine"?

**Comment by allanesquina** [comment]
I prefere Game Engine, and you?

**Comment by ruanltbg** [comment]
@allanesquina I prefere "Game Engine" but who do not know english and will use Google Translator after open the link? They will see: https://translate.google.com/translate?hl=en&sl=en&tl=pt&u=http%3A%2F%2Fmelonjs.org%2F&sandbox=1
"melão JS Um motor de jogo leve HTML5".

**Comment by allanesquina** [comment]
Hi @ruanltbg , sorry the delay, I agree with you, we can't translate technical terms, the most problems of the translations is that they translate it, so, lets keep the original terms. 
I'll revise all soon. 
Thanks for all. :+1:

**Comment by ruanltbg** [comment]
@allanesquina did you review? If you want I can rewrite with english words, but I really do not know which is best.
