### ISSUE TITLE
Encoding issue of public german files

### ISSUE THREAD

**Issue by Pyrax** [braziljs/js-the-right-way#233]
The generated [index.html](https://github.com/braziljs/js-the-right-way/blob/master/public/de-de/index.html) of the german translation seems to have some encoding issue as german umlauts (ü,ä,ö, ...) got replaced by question marks.
I think it's an issue of conversion/generation as the original files seem fine.

**Comment by tbreuss** [comment]
Should be fixed with my pull request https://github.com/braziljs/js-the-right-way/pull/243.

**Comment by allanesquina** [comment]
Files need to be saved with UTF-8 encoding.
Solved :+1:
