### ISSUE TITLE
Add Tape to the list of Testing Tools

### ISSUE THREAD

**Issue by Restuta** [braziljs/js-the-right-way#244]
[Tape](https://github.com/substack/tape) is a [rising star](https://medium.com/javascript-scene/why-i-use-tape-instead-of-mocha-so-should-you-6aa105d8eaf4#.76f9ibl1e) for testing and deserves to be added. 
Maintained by https://github.com/substack

What are the contributor's guidelines? I see some PR's for all the Languages. I am not sure I have time/skills to translate, should I submit PR for just ENG or it's mandatory to cover all languages?
## 

[More reading on Ponyfoo](https://ponyfoo.com/articles/testing-javascript-modules-with-tape)

**Comment by allanesquina** [comment]
Hey @Restuta, thanks, actually we haven't guidelines yet, as the project grown up fast. That's a good idea to implement it now. Don't worries about the translation, the content will be in English if it has not a specific translation. 
Thanks :+1:
