### ISSUE TITLE
Website no longer up?

### ISSUE THREAD

**Issue by andysaini** [braziljs/js-the-right-way#249]
Unable to reach the website.. anyone else facing this?

**Comment by laukstein** [comment]
Is down for me too.
http://www.downforeveryoneorjustme.com/jstherightway.org shows down too.

**Comment by ishanjain28** [comment]
Its probably fixed by now. I can access it. and its up.

**Comment by allanesquina** [comment]
Sorry guys, we're having problems with the server, there was a **datacenter migration**. We're researching another solution for now. Someone knows any option with `WHM` and `CPANEL` :question: 
Thanks!

**Comment by andysaini** [comment]
@allanesquina is the website hosted at github pages?

**Comment by andysaini** [comment]
seems to be up now!
