### ISSUE TITLE
add GSAP in Animation section?

### ISSUE THREAD

**Issue by mauriciomassaia** [braziljs/js-the-right-way#253]
[GSAP (GreenSock Animation Platform)](http://greensock.com/gsap) is robust, easy to use, has a impressive performance and a lot o handy plugins.

Have a look.

Cheers

**Comment by allanesquina** [comment]
Yeah, very interesting, it has a great example [here](http://greensock.com/?example=howls-moving-castle). 
Are you comfortable to add it?
Thanks @mauriciomassaia :+1:

**Comment by marciopuga** [comment]
I've added it, let me know if there is any issue.
