### ISSUE TITLE
Add WhitestormJS to the list of Game Engines

### ISSUE THREAD

**Issue by sasha240100** [braziljs/js-the-right-way#264]
Github: https://github.com/WhitestormJS/whitestorm.js
Documentation: http://whitestormjs.xyz/

**Comment by allanesquina** [comment]
Hi @sasha240100 , I think this project has a great potential, but seems like a growing engine yet since it has too many features to be done, so how about we create a specific section to put projects like this?
Thanks :+1:

**Comment by sasha240100** [comment]
@allanesquina Sure, if you want - off course. But i suggest to put it game engines too. Thank you:)

**Comment by sasha240100** [comment]
@allanesquina Any updates on this topic?

**Comment by allanesquina** [comment]
Hi @sasha240100, Yeah, you've been worked hard, the docs is pretty, I'm gonna put it on game engine section :)
Thanks :+1:

**Comment by sasha240100** [comment]
@allanesquina Nice to hear that from you, thanks:)

**Comment by sasha240100** [comment]
@allanesquina Any updates on this issue?

**Comment by sasha240100** [comment]
@allanesquina Any updates?

**Comment by sasha240100** [comment]
Have it been added?

**Comment by sasha240100** [comment]
@allanesquina ?

**Comment by allanesquina** [comment]
Hey @sasha240100, sorry the delay, I didn't put yet, but you can create a PR with this change, I'll be glad to accept that for sure. How about that?

**Comment by sasha240100** [comment]
@allanesquina Thanks! Will do in 15 mins

**Comment by sasha240100** [comment]
@allanesquina @gnuwilliam I can make a PR, but i don't know where to start from. Is there an instruction?

**Comment by sasha240100** [comment]
@allanesquina @gnuwilliam Done.

**Comment by allanesquina** [comment]
:+1:

**Comment by sasha240100** [comment]
@allanesquina Thanks for adding it! How about making a `build`? It seems it isn't shown on website now
