### ISSUE TITLE
Error imagens 404 when a change language 

### ISSUE THREAD

**Issue by Kirmayrtomaz** [braziljs/js-the-right-way#289]
With you try translate the website for other languagem like portuguese. Any imagens was had 404 

![](http://i.imgur.com/Q6vkpfZ.png)

the problems have because a error for url 

**Error 404**
``` 
http://jstherightway.org/pt-br/assets/img/rollup-logo.png
```
**remove /pt-br/**
Try without directory language and works 
``` 
http://jstherightway.org/assets/img/rollup-logo.png
```

After i clone the repository and test your project searching this bug, but a not found. Works correct

Maybe i think  just need, deploy your repository

**Comment by ruanltbg** [comment]
@Kirmayrtomaz everything is fine here. Can you check again?

**Comment by allanesquina** [comment]
Hi, it could be a DNS problem or something like that. I can't reproduce here but thanks for the warning :+1:
